version: '3.8'

services:
  db:
    image: postgres:15
    container_name: identity_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: identity_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: identity_service_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      context: ./web-app
    container_name: identity_service_frontend
    restart: always
    ports:
      - "5173:4173"
    depends_on:
      - backend

volumes:
  postgres_data:
