spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service
    username: root
    password: root

outbound:
  identity:
    client-id: 190520017829-gssds13l46gl76d550gllc4rblac53mn.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:3000/authenticate
    grant_type: authorization_code

jwt:
  secret: IVb93oUxjFmR7WlDHdW/zANgwk+iytqYAYjmhfR3qy9kR9ADaEnC3Gvz2OMPKRlW
  issuer: akathuatphan
  expiry-seconds: 3600

admin:
  username: admin-identity
  password: Bb123??@
